export enum ActionTypesCart {
	ADD_ITEM = 'ADD_ITEM',
	REMOVE_ITEM = 'REMOVE_ITEM',
	CHANGE_COUNT = 'CHANGE_COUNT',
	CALCULATE_TOTAL_COST_COUNT = 'CALCULATE_TOTAL_COST_COUNT',
	CLEAR_CART = 'CLEAR_CART',
}

export enum ActionTypesPizza {
	SET_FILTER = 'SET_FILTER',
	SET_SORT = 'SET_SORT',
}
